---
steps:
  - name: quant
    image: ghcr.io/ggerganov/llama.cpp:full
    environment:
      MODEL_DIR: /data
      QUANTS: "Q2_K Q5_K_M Q4_K_M Q8_0"
      THREADS: "16"
      VOCAB_TYPE: hfft
      ## HF Repo path:
      #SOURCE: "nold/model-name"
      
    commands:
      - pip3 install -U "huggingface_hub[cli]"
      - /bin/bash /quantizer.sh
    secrets:
      - hf_token
    volumes:
      - /data
